site_name: cstd
site_description: Enhanced C standard-style containers
site_url: https://voidptrr.github.io/cstd/
repo_url: https://github.com/voidptrr/cstd
repo_name: voidptrr/cstd
docs_dir: docs
site_dir: build
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - toc.follow
  font:
    text: Inter
    code: JetBrains Mono
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: false
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
nav:
  - cstd:
      - Overview: index.md
      - cstd.status: reference/cstd-status.md
      - cstd.datastruct:
          - Overview: reference/cstd-datastruct.md
          - cstd.datastruct.vector: data-structures/vector.md
          - cstd.datastruct.queue: data-structures/queue.md
          - cstd.datastruct.linked_list: data-structures/linked-list.md
          - cstd.datastruct.benchmarks: benchmarks.md
