site_name: ckit
site_description: "Documentation for ckit"
site_author: "voidptrr"
edit_uri: "edit/main/docs/docs/"

theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.path
    - navigation.instant
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: "Switch to dark Mode"
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: "Switch to light Mode"

repo_url: https://github.com/voidptrr/ckit
repo_name: voidptrr/ckit

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: ¶

plugins:
  - search

nav:
  - Overview: index.md
  - Compare: reference/ckit-compare.md
  - Memory:
      - Allocators:
          - Overview: reference/ckit-memory-allocators.md
          - Free-list allocator: reference/ckit-memory-general-heap.md
      - Bytes: reference/ckit-memory-bytes.md
  - Data structures:
      - Hashmap: data-structures/hashmap.md
      - Binary heap: data-structures/binary-heap.md
      - Vector: data-structures/vector.md
      - Deque: data-structures/deque.md
      - Linked list: data-structures/linked-list.md
      - String: data-structures/string.md
