name: vstd

on:
  pull_request:
    branches:
      - main
    paths:
      - docs/**
      - src/**
      - tests/**
      - tooling/**
      - flake.nix
      - flake.lock
      - .github/workflows/flake.yml
      - .clang-format
      - .clang-tidy

concurrency:
  group: pre-merge-checks
  cancel-in-progress: true

jobs:
  flake:
    uses: voidptrr/vtools/.github/workflows/checks.yml@67ebc2f56d6536f9d37c65b249c8c51b2dbcf511
