name: pre-merge 

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "src/**"
      - "tests/**"
      - "tooling/**"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/pre-merge.yml"
      - ".clang-format"

concurrency:
  group: pre-merge-checks
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16

      - run: nix develop -c scripts/format-check
      - run: nix develop -c scripts/code-check
      - run: nix develop -c scripts/docs-build
